name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#on:  
#  push:
#  pull_request:
#    branches:
#      - master
on: [push, pull_request]
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        smalltalk: [ Pharo-7.0, Pharo64-7.0, Pharo32-8.0, Pharo64-8.0, Pharo64-9.0, Pharo64-stable, Pharo64-alpha]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15
